# -*- coding: utf-8 -*-
"""Task 1 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QU0N59akLAnugyk6ciONNKzp45_3C04Y
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/big data analysis/samplesuperstore.csv")

df.head()

df.info

df.describe()

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

df.dtypes

df["Delivery Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

print(df.head())

print(df["Category"].unique())

print(df.isnull().sum())

category_sales = df.groupby("Category")["Sales"].sum()
print(category_sales)

plt.figure(figsize=(6,4))
plt.bar(category_sales.index, category_sales.values)
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.show()

plt.figure(figsize=(6,4))
plt.hist(df["Sales"], bins=20)
plt.title("Distribution of Sales")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.show()