# -*- coding: utf-8 -*-
"""task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p60gZGrMFE6kd-S7ouDZAZde2y_UDs6P
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/big data analysis/samplesuperstore.csv")

df.head()

df.info

df.describe()

df["Order Date"] = pd.to_datetime(df["Order Date"])
df["Ship Date"] = pd.to_datetime(df["Ship Date"])

df.dtypes

df["Delivery Days"] = (df["Ship Date"] - df["Order Date"]).dt.days

print(df.head())

print(df["Category"].unique())

print(df.isnull().sum())

plt.figure(figsize=(6,4))
plt.hist(df["Sales"], bins=20)
plt.title("Distribution of Sales")
plt.xlabel("Sales")
plt.ylabel("Frequency")
plt.show()

category_sales = df.groupby("Category")["Sales"].sum()
print(category_sales)

plt.figure(figsize=(6,4))
plt.bar(category_sales.index, category_sales.values)
plt.title("Sales by Category")
plt.xlabel("Category")
plt.ylabel("Sales")
plt.show()

sns.barplot(
    data=df,
    x="Category",
    y="Profit"
)

plt.title("Profit by Category")
plt.xlabel("Category")
plt.ylabel("Profit")
plt.show()

sns.barplot(
    data=df,
    x="Category",
    y="Sales"
)

plt.title("Sales Distribution by Category")
plt.show()

sns.boxplot(
    data=df,
    y="Profit"
)

plt.title("Profit Distribution")
plt.ylabel("Profit")
plt.show()

sns.boxplot(
    data=df,
    x="Category",
    y="Profit"
)

plt.title("Profit Variation Across Categories")
plt.xlabel("Category")
plt.ylabel("Profit")
plt.show()

df["Discount"].unique()

sns.scatterplot(
    data=df,
    x="Discount",
    y="Profit"
)

plt.title("Impact of Discount on Profit")
plt.show()

numeric_df = df.select_dtypes(
    include="number"
)

corr = numeric_df.corr()

sns.heatmap(
    corr,
    annot=True
)

plt.title("Correlation Heatmap")
plt.show()